import React, { useState } from 'react';
import { generateSpeech } from '../services/geminiService';
import { base64ToUint8Array, decodeAudioData } from '../utils/audioUtils';
import { IconVolumeUp, IconSend } from './icons';
import { ProcessingState } from '../types';

export const TTSInterface: React.FC = () => {
  const [text, setText] = useState('');
  const [status, setStatus] = useState<ProcessingState>({ isLoading: false, error: null });

  const handleGenerate = async () => {
    if (!text.trim()) return;
    setStatus({ isLoading: true, error: null });

    try {
      const audioBase64 = await generateSpeech(text);
      const audioCtx = new (window.AudioContext || (window as any).webkitAudioContext)({ sampleRate: 24000 });
      const audioBuffer = await decodeAudioData(
        base64ToUint8Array(audioBase64),
        audioCtx,
        24000,
        1
      );
      
      const source = audioCtx.createBufferSource();
      source.buffer = audioBuffer;
      source.connect(audioCtx.destination);
      source.start();

    } catch (err: any) {
      setStatus({ isLoading: false, error: err.message });
    } finally {
      setStatus(prev => ({ ...prev, isLoading: false }));
    }
  };

  return (
    <div className="h-full flex flex-col p-6 bg-white rounded-lg shadow-sm border border-gray-100">
      <div className="mb-6">
         <h2 className="text-2xl font-bold text-gray-800">Text to Speech</h2>
         <p className="text-gray-500">Gemini 2.5 Flash TTS</p>
      </div>

      <div className="flex-1 flex flex-col space-y-4">
        <textarea
          value={text}
          onChange={(e) => setText(e.target.value)}
          placeholder="Enter text to speak (Urdu or English)..."
          className="w-full h-48 bg-gray-50 border border-gray-200 rounded-xl p-4 focus:ring-2 focus:ring-indigo-500 focus:bg-white transition-all resize-none font-urdu text-lg"
        />
        
        <div className="flex justify-end items-center space-x-4">
            {status.error && <span className="text-red-500 text-sm">{status.error}</span>}
            <button
                onClick={handleGenerate}
                disabled={status.isLoading || !text.trim()}
                className="flex items-center space-x-2 bg-indigo-600 text-white px-6 py-3 rounded-full hover:bg-indigo-700 disabled:opacity-50 transition-colors shadow-sm"
            >
                {status.isLoading ? (
                    <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                ) : (
                    <>
                        <IconVolumeUp />
                        <span>Speak</span>
                    </>
                )}
            </button>
        </div>
      </div>
      
      <div className="mt-8 p-6 bg-indigo-50 rounded-xl border border-indigo-100">
         <h3 className="font-semibold text-indigo-900 mb-2">Usage Tip</h3>
         <p className="text-indigo-700 text-sm">
            Enter Urdu text like "میرا نام منظور ہے" to hear the natural Urdu pronunciation generated by the model.
         </p>
      </div>
    </div>
  );
};
